
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(forcats)
library(pander)
library(quantmod)
library(stringr)
library(SpatialEpi)
library(maps)
library(shapefiles)
library(maptools)
library(RColorBrewer)
library(spdep)
# library(INLA)
library(rgdal)
library(pander)
library(DCluster)
library(geoR)
library(sp)
library(splancs)
# library(GWmodel)
library(psych)
library (cluster)
library(reshape)
library(reshape2)
library(som)
library(GPArotation)
library(corrplot)
library(GGally)
library(faraway)
library(sjPlot)
library(lattice)
library(png)
library(grid)
library(gridExtra)
library(rgeos)
library(leaflet)
library(tigris)
library(broom)
library("broom.mixed")
library(rmapshaper)
library(ggpubr)
library(lme4)
library(lmerTest)
library(stargazer)
library(arm)
library(pscl)
library(spatialreg)
library(ggstance)
library(viridis)
library(ggpubr)
library(ggrepel)
library(readxl)
library(mapview)
library(leafsync)
options(tigris_use_cache = TRUE, tigris_class = "sf")
sf_use_s2(FALSE)

# uploading library 
lapply(c("spatstat","colorRamps","tmap","ggmap","mapview","geoR","knitr","kableExtra","data.table","gdata","tigris","sf","scales","tidycensus","plotly", "tidyverse", "lubridate", 'caret', 'Hmisc', 'RANN'), require, character.only = TRUE)

load("./data/top_decile_enverus.RData") # enverus_county_total
load("./data/tri_county_enverus.RData") # tricounty
